name: Deploy Todolist App

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: self-hosted  # Usa el self-hosted runner configurado en mi instancia de Google Cloud

    steps:
      #Compilación 
      # Verifica el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
      #Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: "16"
            registry-url: "https://registry.npmjs.org"
      #Instalar dependencias
      - name: Install dependencies
        run: npm install
      #Construye laimagen del docker
      - name: Build Docker image
        run: |
          cd ToDo
          sudo docker build -t todo-todolist .
      # Instalar docker compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      #Prueba
      - name: Run tests
        run: |
          npm test
      #Despliegue
      - name: Git pull
        run: |
          cd /home/miisao1325cx_gmail_com/Tarea_Linux/ToDo
          git pull
      # Levantar docker
      - name: Start application-specific services using Docker Compose
        run: |
          cd ToDo
          sudo docker-compose down --volumes
          sudo docker-compose build
          sudo docker-compose up -d
      