name: Deploy Todolist App

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: self-hosted  # Usa el self-hosted runner configurado en tu instancia de Google Cloud

    steps:
      # Paso 1: Verifica el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 5: Desplegar la aplicación en el entorno en la nube
      - name: Start application-specific services using Docker Compose
        run: |
          cd ToDo
          docker-compose up -d  # Levantar la nueva versión
